# Generated by Django 4.2.20 on 2025-04-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('temp', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('precipitation', models.FloatField()),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
