# Generated by Django 4.2.20 on 2025-04-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0003_weatherforecast_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherforecast',
            name='date',
            field=models.DateTimeField(unique=True),
        ),
    ]
